services:
  - type: web
    name: herya-backend
    runtime: node
    repo: https://github.com/spidevmax/herya-app
    rootDir: herya-app-backend

    buildCommand: npm ci
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: DB_URL
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false

    healthCheckPath: /
    autoDeploy: true
